---
# file: roles/k3s-server/tasks/main.yml
- name: Download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    mode: '0755'
- name: create /etc/systemd/system/k3s.service.env
  template:
    src:  k3s.service.env.j2
    dest: /etc/systemd/system/k3s.service.env
    owner: root
    group: root
    mode: '0644'
- name: Copy /etc/systemd/system/k3s.service
  template:
    src:  k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: '0755'
- name: start k3s
  systemd:
    state: started
    name: k3s
    daemon_reload: yes
    enabled: yes
- name: Get k3s node-token
  shell: "cat /var/lib/rancher/k3s/server/node-token"
  register: k3s_node_token
- name: Copy /etc/rancher/k3s/k3s.yaml from controller-0
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/transfer/kube-config"
    flat: yes
