---
# file: roles/k3s-server/tasks/main.yml
- name: Download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    mode: '0755'
- name: create /etc/systemd/system/k3s.service.env 
  template:
    src:  k3s.service.env.j2
    dest: /etc/systemd/system/k3s.service.env
    owner: root
    group: root
    mode: '0644'
- name: Copy /etc/systemd/system/k3s.service
  template:
    src:  k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: '0755'
- name: start k3s
  systemd:
    state: started
    name: k3s
    daemon_reload: yes
    enabled: yes
